### ISSUE TITLE
RFE: pyenv update should regenerate shims unconditionally

### ISSUE THREAD

**Issue by PAStheLoD** [pyenv/pyenv-update#15]
I've bumped into the issue raised in pyenv/pyenv#957, and the root cause seems to be that pyenv update does not regenerate the shims, and eventually incompatible shims are left intact.

**Comment by mwmg** [comment]
I agree with @ssbarnea , I've encountered this bug for the second time now. Running `pyenv rehash` fixes it luckily, but this is something that should be done automatically.
**Edit**: a similar issue seems to be open in pyenv/pyenv#1716.
