### ISSUE TITLE
fatal: could not create leading directories of '/plugins/pyenv-update': Read-only file system

### ISSUE THREAD

**Issue by ssbarnea** [pyenv/pyenv-update#16]
Very recently (2-3 days ago) I got the following error when I open a new shell (MacOS-latest):
```
fatal: could not create leading directories of '/plugins/pyenv-virtualenv': Read-only file system
fatal: could not create leading directories of '/plugins/pyenv-update': Read-only file system
```

Nothing changed and googling reported nothing. To be honest I am not surprised that these paths are invalid, thus being "read only". I am not sure what is causing this problem with pyenv as I see it only with plugins, other stuff seems to be working fine.

**Comment by native-api** [comment]
Looks like the `PYENV_ROOT` envvar is not set.

To say more, I'd need diagnostic info as per https://github.com/pyenv/pyenv/blob/master/.github/ISSUE_TEMPLATE.md .
