### ISSUE TITLE
support to change the code source of pyenv and all its plugins

### ISSUE THREAD

**Issue by JohnHerry** [pyenv/pyenv-update#17]
A new feature is need for this tool.

   We had previously download and install pyenv and its plugins with pyenv-installer, all code are downloaded from "github.com". But now, for some reason, we can not access github.com directly, so we had to update the pyenv from code in 'hub.fastgit.xxx' like, to install newer version of python.

   Will there be any support to run "pyenv update" on specified souce? then we can "git pull" from my specified code source. or else I should change each file in the .git path, replacing "github.com" to "hub.fastgit",  by hand.  It is wearisome, and  it is dangerous for the pyenv I had installed.

**Comment by native-api** [comment]
Since Pyenv-Update does a `git pull`, it will update from wherever you initially cloned Pyenv and its plugins from.

**Comment by native-api** [comment]
Likewise, if you wish to change the update source postfactum, you need to [change the Git remote's URL](https://stackoverflow.com/questions/2432764/how-to-change-the-uri-url-for-a-remote-git-repository) in the affected repo(s).
(Or just clone them anew.)

**Comment by JohnHerry** [comment]
> Likewise, if you wish to change the update source postfactum, you need to [change the Git remote's URL](https://stackoverflow.com/questions/2432764/how-to-change-the-uri-url-for-a-remote-git-repository) in the affected repo(s). (Or just clone them anew.)

Thank you very much.  It works.

All plugins are ok except the `pyenv-installer`, which had 'http://github.com' hard code in the script. but it seems affect nothing on my work, Thank you again!

**Comment by JohnHerry** [comment]
> Likewise, if you wish to change the update source postfactum, you need to [change the Git remote's URL](https://stackoverflow.com/questions/2432764/how-to-change-the-uri-url-for-a-remote-git-repository) in the affected repo(s). (Or just clone them anew.)

Thank you very much.  It works.

All plugins are ok except the `pyenv-installer`, which had 'http://github.com' hard code in the script. but it seems affect nothing on my work, Thank you again!
