### ISSUE TITLE
This does not appear to work.

### ISSUE THREAD

**Issue by Stokestack** [pyenv/pyenv-update#20]
I get:

pyenv: no such command `update'

**Comment by native-api** [comment]
This means that the plugin is not installed or is installed incorrectly. The README has installation instructions.

To be able to say more, we'd need diagnotic information as per https://github.com/pyenv/pyenv/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Stokestack** [comment]
Thanks for the reply! Is there any reason to use this if you've installed Pyenv with Homebrew?

**Comment by native-api** [comment]
Only if you have other plugins.

You need to install plugins into `$PYENV_ROOT/plugins`, even if Pyenv itself is installed elsewhere.

**Comment by Stokestack** [comment]
Thanks. Closing.
