### ISSUE TITLE
Fail to merge: "merge: origin - not something we can merge"

### ISSUE THREAD

**Issue by bkbncn** [pyenv/pyenv-update#22]
after #19, I got fail to merge the main pyenv repo, but the rest repos are normal to merge.

the git error message is `merge: origin - not something we can merge`
```
❯ pyenv update
Updating /Users/Xiangyu/.pyenv...
From https://github.com/pyenv/pyenv
 * branch              master     -> FETCH_HEAD
merge: origin - not something we can merge
Updating /Users/Xiangyu/.pyenv/plugins/pyenv-doctor...
From https://github.com/pyenv/pyenv-doctor
 * branch            master     -> FETCH_HEAD
Already up to date.
Updating /Users/Xiangyu/.pyenv/plugins/pyenv-update...
From https://github.com/pyenv/pyenv-update
 * branch            master     -> FETCH_HEAD
Already up to date.

```

**Comment by native-api** [comment]
According to https://stackoverflow.com/questions/16862933/how-to-resolve-gits-not-something-we-can-merge-error , this can mean that you've removed the 'origin' remote from the repo.

The easiest fix would probably be to delete `~/.pyenv` and clone it anew. Move the stuff you want to preserve out before deleting, of course (probably `~/.pyenv/versions` and `~/.pyenv/plugins` except `~/.pyenv/plugins/python-build`).

**Comment by tekumara** [comment]
I'm hitting this too:
```
rm -rf ~/.pyenv
curl -fsSL https://pyenv.run | bash
pyenv update
....
merge: origin - not something we can merge
```

On the line where `pyenv update` runs [git merge --ff origin master](https://github.com/pyenv/pyenv-update/blob/39b088e56c0b176a50a700bfcfe91fa6428ee8b9/bin/pyenv-update#L68). 

I think it's because there is no `origin/HEAD` branch. If that exists, `git merge -ff origin master` works.

**Comment by tekumara** [comment]
So I've noticed this doesn't happen with git 2.43.0 but it does happen with git 2.49.0

For some reason a clone using git 2.43.0 will create a `origin/HEAD`. And so `git merge --ff origin master` (which is shorthand for `git merge --ff origin/HEAD master`) succeeds.

**Comment by tekumara** [comment]
So I've noticed this doesn't happen with git 2.43.0 but it does happen with git 2.49.0

For some reason a clone using git 2.43.0 will create a `origin/HEAD`. And so `git merge --ff origin master` (which is shorthand for `git merge --ff origin/HEAD master`) succeeds.

I think if pyenv were to use `git merge --ff origin/master` it would reliably work across git versions.

**Comment by tekumara** [comment]
So I've noticed this doesn't happen with git 2.43.0 but it does happen with git 2.49.0

For some reason a clone using git 2.43.0 will create a `origin/HEAD`. And so `git merge --ff origin master` (which is shorthand for `git merge --ff origin/HEAD master`) succeeds.

I think if pyenv update were to use `git merge --ff origin/master` it would reliably work across git versions.

**Comment by tekumara** [comment]
Pending the fix mentioned above, I'm running this after installing pyenv to make pyenv update work:
```
    # Add origin/HEAD to each git repository in ~/.pyenv
    for repo in ~/.pyenv/plugins/*/ ~/.pyenv/; do
        if [[ -d "$repo/.git" ]]; then
            (cd "$repo" && git remote set-head origin -a)
        fi
    done
```
