### ISSUE TITLE
"pyenv update" not fetching latest versions supplied by pyenv

### ISSUE THREAD

**Issue by nickeldan** [pyenv/pyenv-update#25]
pyenv added 3.12.1 [a month and a half ago](https://github.com/pyenv/pyenv/pull/2861).  However, even after I run `pyenv update`, the latest version shown is still 3.12.0.

**Comment by e10sgits** [comment]
I also have an issue where one of my MacBooks has a `pyenv update` and the other one doesn't. I know this because I run the `Pyenv` command on both and between uninstall and versions is listed `update` on one Macbook but not the other.

When `pyenv update` is ran the prompt "'update' command not found.'"

**Comment by nickeldan** [comment]
> I also have an issue where one of my MacBooks has a `pyenv update` and the other one doesn't. I know this because I run the `Pyenv` command on both and between uninstall and versions is listed `update` on one Macbook but not the other.
> 
> When `pyenv update` is ran the prompt "'update' command not found.'"

Do you have the pyenv-update plugin installed as well?

**Comment by e10sgits** [comment]
I may not how can I do this?

**Comment by e10sgits** [comment]
I may have missed a step the installing it on my second laptop.

**Comment by native-api** [comment]
@nickeldan what does your `which -a pyenv` show?

**Comment by e10sgits** [comment]
pyenv () {
	local command
	command="${1:-}" 
	if [ "$#" -gt 0 ]
	then
		shift
	fi
	case "$command" in
		(activate | deactivate | rehash | shell) eval "$(pyenv "sh-$command" "$@")" ;;
		(*) command pyenv "$command" "$@" ;;
	esac
}
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv

**Comment by e10sgits** [comment]
> @nickeldan what does your `which -a pyenv` show?

pyenv () {
local command
command="${1:-}"
if [ "$#" -gt 0 ]
then
shift
fi
case "$command" in
(activate | deactivate | rehash | shell) eval "$(pyenv "sh-$command" "$@")" ;;
(*) command pyenv "$command" "$@" ;;
esac
}
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv
/Users/ethanavendanoo/.pyenv/bin/pyenv


This is on the laptop that it worked on. I was able to figure out the issue though thank you for taking time out of your day to respond though thank you.

**Comment by native-api** [comment]
@e10sgits Your problem is different, you need to [install the plugin](https://github.com/pyenv/pyenv-update?tab=readme-ov-file#installation).

**Comment by e10sgits** [comment]
Yes, thank you.

**Comment by e10sgits** [comment]
> @e10sgits Your problem is different, you need to [install the plugin](https://github.com/pyenv/pyenv-update?tab=readme-ov-file#installation).

Yes, thank you.

**Comment by native-api** [comment]
@nickeldan Please also attach the output of `PYENV_DEBUG=1 pyenv update` as a gist.

**Comment by brunosavyofs** [comment]
> pyenv added 3.12.1 [a month and a half ago](https://github.com/pyenv/pyenv/pull/2861). However, even after I run `pyenv update`, the latest version shown is still 3.12.0.

Have you managed to install version 3.12.1 with pyenv?

**Comment by nickeldan** [comment]
Huh.  It's now showing 3.12.1 and 3.12.2.  Oh, well.
